name: Build and Create .exe

on:
  push:
    branches:
      - master
      - dev
      - feature/*
  pull_request:
    branches:
      - master
      - dev
      - feature/*

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Étape 1 : Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Étape 2 : Vérification du code
      - name: Run unit tests
        run: |
          python -m unittest discover -s ./src/test/python

      # Étape 3 : Compilation du projet
      - name: Build solution
        run: python -m PyInstaller --onefile --windowed --icon=jeu-de-la-vie.ico --name=Jeu_de_la_Vie --add-data="src/main/resources/dimensions.json;resources" --add-data="src/main/resources/languages/en.json;resources/languages" --add-data="src/main/resources/languages/fr.json;resources/languages" .\src\main\python\main.py

      # Étape 4 : Archivage de l'exécutable
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: Jeu_de_la_Vie
          path: dist/Jeu_de_la_Vie.exe
